name: GitHub Activity

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@de571a42629d5d44f59ac5055db94d3f7f362438
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
